### ISSUE TITLE
Bosh manifest description lack useful networking details from oss-docs

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-bosh#1]
http://docs.cloudfoundry.org/bosh/create-manifest.html#networks is currently lacking some useful Iaas independent details that are still available at
https://github.com/cloudfoundry-attic/oss-docs/blob/master/bosh/documentation/bosh_deployments.md#network-spec such as the difference between manual and dynamic networks, and the static and dynamic ip pools

The Iaas specific pages don't document these common parts

**Comment by cppforlife** [comment]
Detailed description written up: http://docs.cloudfoundry.org/bosh/networks.html

**Comment by gberche-orange** [comment]
thanks !
