### ISSUE TITLE
Documented IAM permissions don't allow uploading non-light stemcell

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/docs-bosh#132]
We use:

https://github.com/pivotal-cf-experimental/bosh-bootloader/blob/fbb54ff/aws/cloudformation/templates/bosh_iam_template_builder.go#L17-L52

Copied from:

http://bosh.io/docs/aws-iam-users.html#create (Step 10)

Needed to add stuff around registering image.

Original issue that surfaced this:

https://github.com/pivotal-cf-experimental/bosh-bootloader/issues/16

**Comment by dpb587-pivotal** [comment]
True; hadn't used that. Should add `RegisterImage` and `DeregisterImage`.

**Comment by cppforlife** [comment]
Added in 40773b6089d84eaf55b55dded752813d91005d0f
