### ISSUE TITLE
wrong title of the "director-configure-blobstore.html"

### ISSUE THREAD

**Issue by warmchang** [cloudfoundry/docs-bosh#156]
Hi,
Chapters "Configuring external blobstore" and "Configuring external database" have the same title (Connecting the Director to an External Postgres Database).
In fact, the following text should be not the "External Postgres Database", and "External Blobstore" is better.

    ---
    title: Connecting the Director to an External Postgres Database
    ---

If you conform it, I will submit the PR for "https://github.com/cloudfoundry/docs-bosh/blob/master/director-configure-blobstore.html.md.erb".

**Comment by cppforlife** [comment]
Updated. Thanks.
