### ISSUE TITLE
Typo in docs description of job templates

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/docs-bosh#167]
Hi,

I noticed that there is a typo/missing words in the description of `templates` and how they are related to `jobs`. 

Here is the line in the docs: https://github.com/cloudfoundry/docs-bosh/blob/master/jobs.html.md.erb#L54
Here is the section of the web page on bosh.io: https://bosh.io/docs/jobs.html#templates

**Comment by glyn** [comment]
Just to be clear, I believe the problem sentence is "A template is a file that can b."

**Comment by johnsonj** [comment]
@cppforlife may want to take a look at this one

**Comment by cppforlife** [comment]
Removed. Thanks.
