### ISSUE TITLE
Ubuntu trusty installation instructions do not work

### ISSUE THREAD

**Issue by rvandegrift** [cloudfoundry/docs-bosh#171]
The bosh_cli instructions mention that ruby 2+ is required, but the instructions for Ubuntu trusty install ruby 1.9.

Instead of `ruby` and `ruby-dev`, `ruby2.0` and `ruby2.0-dev` should be installed.  Instead of calling `gem` to install, `gem2.0` should be used.

**Comment by dpb587-pivotal** [comment]
Closing - ruby CLI is no longer maintained; feel free to give the [new CLI a try](https://bosh.io/docs/cli-v2#install) which has fewer dependencies.
