### ISSUE TITLE
cloud config page has potentially misleading warning about existing deployments

### ISSUE THREAD

**Issue by craigfurman** [cloudfoundry/docs-bosh#192]
The [cloud config page](http://bosh.io/docs/cloud-config.html) states "Warning: Once you opt into using cloud config all deployments must be converted to use new format. There is no way to opt out of the cloud config once you opt in.".

We were using director v257.3 (the latest at the time of writing) and found that this does not seem to be true, we can redeploy old-style (no cloud config) manifests once cloud config has been uploaded.

**Comment by dpb587-pivotal** [comment]
Related docs fix for this: https://github.com/cloudfoundry/docs-bosh/pull/188

**Comment by cppforlife** [comment]
Warning already fixed.
