### ISSUE TITLE
bosh sample manifest default disk size is to small 

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-bosh#2]
As discussed on https://groups.google.com/a/cloudfoundry.org/d/msg/bosh-users/RHFPYaEy9FE/SKEo8SAICskJ

The bosh sample manifest has invalid default disk sizing
https://github.com/cloudfoundry/docs-bosh/blob/807c02e9ce62dd5fcddfc4a76bed6a8ad2331e91/deploy-with-bosh.html.md.erb#L278

The net effect is that stemcell upload and release upload fail (silently), making it harder for new users to debug and diagnose the issue.

```
 $ bosh upload stemcell ~/code/bosh-stemcell-1471_2-vsphere-esxi-ubuntu.tgz 
Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK
Stemcell info
-------------
Name:    bosh-vsphere-esxi-ubuntu
Version: 1471.2
Checking if stemcell already exists...
No
Uploading stemcell...
bosh-stemcell: 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| 395.9MB 617.5KB/s Time: 00:10:56

gberche@ruby-desktop2 ~/code/integration-configuration-reference/configuration-reference-qa/bosh/deployments/cf04 (master) $ bosh stemcells
No stemcells
gberche@ruby-desktop2 ~/code/integration-configuration-reference/configuration-

```

What about moving the sample manifests out of docs-bosh into https://github.com/cloudfoundry/bosh/tree/master/release/examples and make sure that they get tested as part of CI ?

Also wouldn't it be safer to suggest new users to use ubuntu stemcells rather than centos ones on which there might be less confidences (I'm not sure how to read the status of the centos epic on https://www.pivotaltracker.com/s/projects/956238 and whether it's actually complete)

**Comment by dpb587-pivotal** [comment]
Closing - deployment strategies have changed since the introduction of [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment) and we're a bit more liberal in the default disk sizes. Feel free to open another issue in bosh-deployment if you think there's an ongoing issue.
