### ISSUE TITLE
"Jobs never depend on other jobs" - Outdated Info ?

### ISSUE THREAD

**Issue by pivotal-jamil-shamy** [cloudfoundry/docs-bosh#222]
This [line](https://github.com/cloudfoundry/docs-bosh/blob/master/create-release.html.md.erb#L240) states that `Jobs never depend on other jobs`. But with the introduction of links, seems a bit misleading.

**Comment by d** [comment]
Can you elaborate how you believe BOSH links make jobs depend on each other? I believe the quoted statement is still true

**Comment by dpb587-pivotal** [comment]
I think the statement is still true, but it does seem like a good place where we could link to the pages about links. The page feels like it's trying to more describe how to structure your jobs and packages into logical pieces (whereas links still don't define execution dependencies since properties/ips are deterministic).

**Comment by pivotal-jamil-shamy** [comment]
@d @dpb587-pivotal Taking that page as the context, it is true that jobs do not declare dependency on other jobs the same way packages declare dependencies on other packages. But on the other side, if job "A" declares in its spec that it consumes link "X" (which is most probably provided by another job - excluding manual links), and it cannot proceed with its duties without this information, it becomes dependent on whoever provides that link, i.e. another job.

+1 for adding a link to Bosh Links in that statement. Will do a pull request.

**Comment by d** [comment]
Wrong. A job can declare that it consumes a link and still function without it. The job just needs to have a conditional guarding the evaluation of the `link` helper within the ERB template.

**Comment by pivotal-jamil-shamy** [comment]
:-) 

If a job declares that it consumes a link, and if that link is not provided, the deployment will fail (even if you put guards in your templates using `if_link`, actually even if you don't use that ink at all in you templates).

What you are talking about in your last response is a special case where you will need to declare the link you are consuming as `optional` in the job spec. Then, you can put guards in your template using `if_link`.

**Comment by cppforlife** [comment]
@pivotal-jamil-shamy I heard you are planning to rewrite that page anyway ;)
