### ISSUE TITLE
feature mentioned in tips about pinging unreachable vms is outdated 

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/docs-bosh#225]
On the tips page (https://bosh.io/docs/tips.html) about debugging "unreachable vms", there is mention about a "plan to introduce a feature in the Director to leave unreachable VMs for easier debugging". This feature exists and the text should be updated and point to this page: 

https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p=director.debug.keep_unreachable_vms

**Comment by cppforlife** [comment]
Fixed in afa9c1851f0c5cb9d695764d508b79496bdcecca.
