### ISSUE TITLE
Ambiguity in what update_watch_time includes

### ISSUE THREAD

**Issue by Samze** [cloudfoundry/docs-bosh#235]
From reading the update block[ docs](https://bosh.io/docs/deployment-manifest.html#update) it is unclear whether the update_watch_time includes post-start script running. It doesn't seem to, and that's understandable, but it might be worth pointing this out explicitly in the docs.

Sam & @craigfurman

**Comment by dpb587-pivotal** [comment]
To confirm, `update_watch_time` is only about the time waiting for the monit processes to come up. The pre/post/drain scripts can take as long as they need.

Good idea to update the docs.

**Comment by cppforlife** [comment]
Fixed in  d93d3a99099b9fbe2cabfe70c62b49992f79a573.
