### ISSUE TITLE
Microbosh examples should mention HM user

### ISSUE THREAD

**Issue by hiremaga** [cloudfoundry/docs-bosh#25]
e.g. http://docs.cloudfoundry.org/bosh/deploy-microbosh-to-aws.html

The manifest on this page is missing a section to configure HM to talk to the director. A bosh user needs to be created manually for this to work; i.e. using `bosh create user hm`.

This needs to be configured correctly for the resurrector and agent metrics reporting to work correctly.

This process is similar to replacing the built in an admin account, which also doesn't appear to be described anywhere at this time.

**Comment by cppforlife** [comment]
Since we are moving towards bosh-init, I've update those docs (e.g. http://bosh.io/docs/init-aws.html).
