### ISSUE TITLE
Default generate scripts uses insecure defaults

### ISSUE THREAD

**Issue by tushar-dadlani** [cloudfoundry/docs-bosh#262]
The docs in [this section](https://github.com/cloudfoundry/docs-bosh/blob/18d32d9/director-certs.html.md.erb#L13-L65), generate certs that use    
`Signature Algorithm: sha1WithRSAEncryption`. Among other things it also sends `yes ""` for all answers for certificate generation input. It should use sha256 at least.

/cc @ishustava @bblincoe @bijukunjummen

**Comment by dpb587-pivotal** [comment]
Can add `-sha256` to all the `req` commands.

**Comment by cppforlife** [comment]
covered through config_server/types package.
