### ISSUE TITLE
Template for OpenStack missing 'tenant'

### ISSUE THREAD

**Issue by mcpeak** [cloudfoundry/docs-bosh#263]
The template file used for OpenStack needs a property `tenant` to work properly.  The tenant is apparently the same as `project`, so maybe this changed and `project` is no longer required?

**Comment by mcpeak** [comment]
This is possibly version dependent - I see the document has not been updated since Mitaka.

**Comment by voelzmo** [comment]
@mcpeak `tenant` is a keystone-v2 term. The provided template is a keystone-v3 template. See http://bosh.io/docs/openstack-keystonev2.html for how to switch to keystone-v2.

**Comment by mcpeak** [comment]
@voelzmo Got it, thank you.
