### ISSUE TITLE
Missing documentation: releases section of manifest supports URLs

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/docs-bosh#265]
I'm not sure anymore what variations are supported anymore in the various CLI versions.  At one point, it used to be:

* can specify `latest`, and it will just use what's on the director
* can specify version, and it will use it if it's on the director
* can specify remote tarball URL, along with version and SHA1
* can specify local tarball `file:///` URL, along with version (no need for SHA1)
* can specify local release directory path, along with version `create`, and it will create the release and upload it for you.

I think at minimum all versions of the CLI support the remote URL specification, though not sure whether they treat version and SHA1 the same.  Either way, would be nice to have all the supported fields in the `releases` block of the manifest documented.

/cc @tinygrasshopper

**Comment by dpb587-pivotal** [comment]
Closing - documented at [bosh.io/docs/release-urls](https://bosh.io/docs/release-urls/)
