### ISSUE TITLE
CLI v2 install page should include OS prerequisites 

### ISSUE THREAD

**Issue by pivotal-danjahner** [cloudfoundry/docs-bosh#278]
Installing the v2 CLI on a standard Ubuntu machine using the binaries from [this page][1] doesn't work, due to missing packages. We should include a list of thing to install for this CLI to work, similar to https://bosh.io/docs/bosh-cli.html
[1]:https://bosh.io/docs/cli-v2.html

**Comment by cppforlife** [comment]
i think this was fixed via https://bosh.io/docs/cli-env-deps.html
