### ISSUE TITLE
VPC subnets are not public by default

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/docs-bosh#31]
I followed instructions in this tutorial and all cf instances have only private ip. So they can't download buildpacks and use S3 storage.

To prevent this user should explicitly change `Auto-assign Public IP` subnet property to `yes`.

**Comment by animatedmax** [comment]
Hi lexsys2, 

We've updated the document with instructions on enabling the `Auto-assign Public IP`. The new instructions start here: https://github.com/cloudfoundry/docs-bosh/blob/master/deploy-microbosh-to-aws.html.md.erb#L203

Thank you!

**Comment by animatedmax** [comment]
Hi lexsys2,

Upon further consideration, we're removing the Auto-assign Public IP instructions to reduce possible security issues in production environments.

**Comment by lexsys27** [comment]
So what is the recommended way for nodes to access S3 storage now?

Can you outline here these security considerations? Isn't enough to restrict access with AWS security groups?

**Comment by d** [comment]
@lexsys27 put all your CF vms in a "private" subnet and route traffic to the internet through a NAT box
