### ISSUE TITLE
`director_uuid` is listed as `required` in both V1 and V2 schema, this seems wrong

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/docs-bosh#331]
The [docs for the CLI V2](https://bosh.io/docs/deployment-manifest.html#deployment) clearly state that the V2 cli ignores this attribute:

> bosh deploy no longer checks or requires director_uuid in the deployment manifest to achieve similar safety make sure to give unique deployment names across environments

This is in contradiction with what the schema docs are saying:

Here: https://bosh.io/docs/deployment-manifest.html#deployment
and here: https://bosh.io/docs/manifest-v2.html#deployment

> director_uuid [String, required]: This string must match the UUID of the currently targeted Director for the CLI to allow any operations on the deployment.

I'm guessing this is at least wrong for the V2 schema, not so sure about the V1 schema. Please clarify the docs around when, if ever, the `director_uuid` property is required.

**Comment by cppforlife** [comment]
Updated manifest-v2

**Comment by kdvolder** [comment]
Thanks, but I'm not sure the issue is addressed. Two things:

1. The docs about V2 schema are still wrong. I just checked them again.

2. I wonder if even V1 schema docs might need to be updated to resolve this issue. My guess is that if you deploy a V1 schema with a V2 CLI, the V2 CLI will ignore that property. Is that right? If so, I think V1 schema should probably also have a comment to that effect.

**Comment by dpb587-pivotal** [comment]
Docs have been clarified a little. The `director_uuid` is ignored by directors, so only the old ruby CLI relied on it. Technically, both v1 and v2 style manifests can be deployed with both CLIs; so `director_uuid` may need to be present (we're assuming/promoting people to move away from v1 manifests).
