### ISSUE TITLE
Google CPI documentation does not mention `service_account` parameter

### ISSUE THREAD

**Issue by smgoller** [cloudfoundry/docs-bosh#398]
In the [Google CPI documentation relating to vm-types](http://bosh.io/docs/google-cpi.html#vm-types) the `service_account` parameter is not mentioned at all. This option is necessary for bosh to be able to launch an instance with the permissions of a service account. This option is described in the [bosh resource pool options section](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/master/src/bosh-google-cpi/README.md#bosh-resource-pool-options) of the Google CPI README.

**Comment by dpb587-pivotal** [comment]
Closing - thanks for reporting! PR #401 fixes this and the bosh.io/docs site will be updated shortly.
