### ISSUE TITLE
"Bosh Lite Director" name is not compatible with credhub

### ISSUE THREAD

**Issue by mkuratczyk** [cloudfoundry/docs-bosh#403]
Hi,
The name of the director suggested in this example:
https://github.com/cloudfoundry/docs-bosh/blob/master/bosh-lite.html.md.erb#L52
is not compatible with Credhub - if you add Credhub to your bosh deployment and then try to deploy something using Credhub to generates credentials, it fails because by default credentials will be located under /director_name/deployment_name/credential_name and "Bosh Lite Director" is not a valid path (spaces are not allowed).

**Comment by dpb587-pivotal** [comment]
You're right it's currently an issue. I'm going to close this in favor of #392 which proposes to change it.
