### ISSUE TITLE
[question] What about bosh versions?

### ISSUE THREAD

**Issue by allomov** [cloudfoundry/docs-bosh#41]
Hey, all.

I've always wanted to ask if you are planning to add tags for BOSH versions to your docs? Sometimes it is hard to keep track of the version of BOSH that is described in articles. Hope this will solve this problem.

Thank you,
Alex L.

**Comment by cppforlife** [comment]
I've started adding version descriptions when adding new features. For example: https://bosh.io/docs/director-users.html#preconfigured.

**Comment by allomov** [comment]
Nice to hear. Thank you.
