### ISSUE TITLE
Generate docs

### ISSUE THREAD

**Issue by ronaldpetty** [cloudfoundry/docs-bosh#424]
Hello,

Are there instructions somewhere on how to generate readable docs versus the erb?  Like to read offline.

Regards.

Ron

**Comment by dpb587-pivotal** [comment]
We hope to remove the `*.erb` extension [this week](https://github.com/cloudfoundry/docs-bosh/pull/404#issuecomment-346856263) so they are nicely rendered by GitHub and local editors. In the meantime, there is [a pull request](https://github.com/bosh-io/web/pull/25/files) which documents how they are built for [bosh.io/docs](https://bosh.io/docs/) if you want to try running it locally.

**Comment by ronaldpetty** [comment]
Well that is serendipitous!  Will keep a look out for that.
