### ISSUE TITLE
Wrong example on "Persistent and Orphaned Disks"

### ISSUE THREAD

**Issue by kkitai** [cloudfoundry/docs-bosh#443]
this is not "jobs".  I think that the correct is "instance_groups". right?

    https://github.com/cloudfoundry/docs-bosh/blob/master/persistent-disks.html.md.erb#L43

**Comment by dpb587-pivotal** [comment]
You're right, these job references should be updated to instance group.

Historically, "instance groups" were called "jobs"... there are some old references like this which need to be fixed. Thanks for pointing it out.

**Comment by kkitai** [comment]
@dpb587-pivotal  
oh! I didn't know the historical background. 
thank you.
