### ISSUE TITLE
compilation.env should be documented

### ISSUE THREAD

**Issue by dpb587-pivotal** [cloudfoundry/docs-bosh#472]
Mention `env` in http://bosh.io/docs/cloud-config.html#compilation, probably with a reference to `env` section of http://bosh.io/docs/manifest-v2.html#instance-groups

**Comment by cppforlife** [comment]
was already added:
https://github.com/cloudfoundry/docs-bosh/blob/master/cloud-config.html.md.erb#L250

**Comment by dpb587-pivotal** [comment]
Good, I didn't realize.

It is confusing that the version everyone sees hasn't been updated in 4 weeks though.
