### ISSUE TITLE
Bosh AWS quick start doesn't work as followed because of Elastic IP dependencies

### ISSUE THREAD

**Issue by matthewfischer** [cloudfoundry/docs-bosh#478]
I tried following https://bosh.io/docs/init-aws.html today and ran into issues which I will document here, per convo with Danny Berger on Slack.

1. It is unclear what to do with the Elastic IP that is created. The docs say to "Replace ELASTIC-IP in your deployment manifest with the allocated Elastic IP Address.", but I can't find anything in any sub-folder that looks like ELASTIC_IP with any casing. This causes bosh to fail to ssh to bosh/0 since it's trying to ssh to the internal (private) IP from your AWS subnet.

2. I was pointed to https://bosh.io/docs/init-external-ip.html on slack which seemed to get me past this issue, but I think that the user experience from the original doc is not great. It doesn't work as followed, unless you happened to catch that link to the external ip section.

3. The Common Errors page (https://bosh.io/docs/aws-cpi.html#errors) should probably include this failure to ssh to a local IP address.

I would vote for any of the following solutions:

1. Make the EIP stuff way more obvious - move the notes from init-external-ip onto the main page OR make it an explicit required step so that after allocating the EIP, I know what to do with it.
2. Redesign the process to use a jump box instead and offer directions on this process.

**Comment by dpb587-pivotal** [comment]
Thanks for creating the issue; we should separate out the provisioning steps and the steps for bringing up director.

Originally discussed in [cloudfoundry#bosh](https://cloudfoundry.slack.com/archives/C02HPPYQ2/p1520278915000421).
