### ISSUE TITLE
"Contribute changes to this page" link does not work

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry/docs-bosh#488]
i.e. from release blobstore it goes to https://github.com/cloudfoundry/docs-bosh/blob/master/release-blobstore.html.md.erb
Correct url is https://github.com/cloudfoundry/docs-bosh/blob/master/release-blobstore.md

**Comment by dpb587-pivotal** [comment]
Fixed via recent switch to mkdocs.
