### ISSUE TITLE
Change favicon to new circle logo

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/docs-bosh#499]
Currently the favicon is an awkwardly chopped clam. Long live the clam, but let him be free to be a full clam away from the constraints of a square favicon.

**Comment by dpb587-pivotal** [comment]
Agreed. I suppose we should find another subtle place for the clam to live on.

**Comment by cppforlife** [comment]
clam must live on.

**Comment by dpb587-pivotal** [comment]
s/must/should/

We can find a less official place for it than the favicon.
