### ISSUE TITLE
"bosh deploy" update of VMs blocked by "bosh ssh" - display warning to user?

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/docs-bosh#501]
One behavior I've seen before, and again just now - I run `bosh deploy` to update VMs (e.g. resize them) and the output blocks at `Updating instance <name>...`. Eventually you become suspicious that nothing is happening. Somewhere in your terminal tabs you discover you have a `bosh ssh` session into one of the VMs. You cancel the session and the `bosh deploy` can finally delete the vm.

Could we add something to the `bosh deploy` output which states that it is not going to do the update until the `bosh ssh` sessions are stopped, so you know to go find them and kill them?

**Comment by cppforlife** [comment]
that's interesting that it would block the deploy. is it just plain ssh or were you running something on the system?

**Comment by drnic** [comment]
a) not sure why I raised ticket against docs; b) I’ll try to reproduce

________________________________
