### ISSUE TITLE
The tile "calculate_vm_cloud_properties" isn't shown correctly

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/docs-bosh#503]
The two methods `configure-networks` and `calculate_vm_cloud_properties` are mixed.

https://bosh.io/docs/cpi-api-v1/#configure-networks

**Comment by cppforlife** [comment]
fixed in https://github.com/cloudfoundry/docs-bosh/commit/45d8749f133eb96fa4d6202e526c690281819aad. thanks!
