### ISSUE TITLE
document different disk setup/usage scenarios

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry/docs-bosh#509]

**Comment by cppforlife** [comment]
cc @Amit-PivotalLabs @dsboulder

**Comment by dpb587-pivotal** [comment]
I don't know what documentation and information this is looking for.

**Comment by cppforlife** [comment]
would like to build a table of different IaaS specific disk configurations (root disk, eph disk, persistent disk) and how they relate to encryption options provided by an IaaS.
