### ISSUE TITLE
`calculate_vm_cloud_properties` should have its own heading

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/docs-bosh#523]
On the [CPI API page](https://bosh.io/docs/cpi-api-v1/), there's a bit on `calculate_vm_cloud_properties` but it doesn't have its own heading I can link others to.  Probably should.

/cc @dpb587 @cppforlife @xtreme-andrew-su

**Comment by bingosummer** [comment]
FYI: https://github.com/cloudfoundry/docs-bosh/issues/503. I think, it has been fixed.
https://bosh.io/docs/cpi-api-v1/#calculate-vm-cloud-properties

**Comment by Amit-PivotalLabs** [comment]
@bingosummer that works great, thanks!
