### ISSUE TITLE
Link from `bosh sync-blobs -h` output doesn't work

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/docs-bosh#524]
```
$ bosh sync-blobs -h | grep http
https://bosh.io/docs/cli-v2#sync-blobs
```

Clicking that link just takes me to the top of the [CLI v2+ doc page](https://bosh.io/docs/cli-v2/).  Looks like there is a section on [Release blobs](https://bosh.io/docs/cli-v2/#blob-mgmt) but no way to link specifically to the `sync-blobs` command.

If relevant:

```
$ bosh --version
version 3.0.1-712bfd7-2018-03-13T23:26:42Z
```

**Comment by cppforlife** [comment]
@dpb587-pivotal did we accidently kill all hrefs? i cant seem to find them.

**Comment by bingosummer** [comment]
@dpb587-pivotal 
I also hit the issue. All links don't work.

**Comment by 7hunderbird** [comment]
In the `bosh-cli` repo the `cmd/factory.go` is generating each URL based off the name of the command.

https://github.com/cloudfoundry/bosh-cli/blob/891ff634a896de0839feb5a316d7341fb26ed458/cmd/factory.go#L36-L47

```go
for _, c := range parser.Commands() {
  docsURL := "https://bosh.io/docs/cli-v2#" + c.Name

  c.LongDescription = c.ShortDescription + "\n\n" + docsURL

  fillerLen := 50 - len(c.ShortDescription)
  if fillerLen < 0 {
    fillerLen = 0
  }

  c.ShortDescription += strings.Repeat(" ", fillerLen+1) + docsURL
}
```

Yet in the new [Using the CLI](https://bosh.io/docs/cli-v2/) guide there are less headers.

There are 80 commands to link from.  And when we have the Table of Contents on the right if there were 80 items the list would be too huge.

I'm going to look around some more.  But maybe there's a way we can have a sensible TOC and fix the links too.
