### ISSUE TITLE
Shall we remove the `availability_zone` in cpi vm_types/vm_extensions?

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/docs-bosh#526]
In http://bosh.io/docs/azs/#config, it mentions "Note that IaaS specific cloud properties related to AZs should now be only placed under azs. Make sure to remove them from resource_pools/vm_types cloud properties.". If so, shall we remove the `availability_zone` in [azure cpi vm_types/vm_extensions](http://bosh.io/docs/azure-cpi/#resource-pools)?

Also for other CPIs:
http://bosh.io/docs/aws-cpi/#resource-pools
http://bosh.io/docs/google-cpi/#vm-types
http://bosh.io/docs/openstack-cpi/#resource-pools
http://bosh.io/docs/softlayer-cpi/#resource-pools
http://bosh.io/docs/vsphere-cpi/#resource-pools

**Comment by bingosummer** [comment]
@dpb587-pivotal wdyt?

**Comment by mfine30** [comment]
@dpb587-pivotal I agree with your proposal. I think that makes sense. From a more tactical perspective, what should we do to make those changes? 

But yeah, if we can think of ways to make `create-env` easier, I think that's valuable, but perhaps out of scope for what we should address in this issue?

**Comment by dpb587-pivotal** [comment]
@bingosummer if you want to PR for all CPIs, feel free. If the change for a CPI turns out to be more complex than just removing `availability_zone` from the resource/VM section, leave us a note in the PR for us to look into or work with the other CPI teams.
