### ISSUE TITLE
Document Bosh Director API endpoint for disks

### ISSUE THREAD

**Issue by akskap** [cloudfoundry/docs-bosh#535]
Checked the following [link](https://github.com/cloudfoundry/docs-bosh/blob/master/content/director-api-v1.md) and don't seem to find the API endpoints listed for fetching disks data from the Director. (Additional options like orphaned_disks etc. would also help)

Please let me know if you'd be fine with a Pull Request for these

**Comment by voelzmo** [comment]
For the record: The API endpoints we're talking about here are those of the [`disks_controller`](https://github.com/cloudfoundry/bosh/blob/master/src/bosh-director/lib/bosh/director/api/controllers/disks_controller.rb)
