### ISSUE TITLE
Performance of the multi-cpi scenario

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/docs-bosh#539]
In [guide-multi-cpi-aws.md](https://github.com/cloudfoundry/docs-bosh/blob/master/content/guide-multi-cpi-aws.md), the single deployment is across two regions: `US East` and `US West`.
Two questions:
* The internal traffic between different components may go from `US East` to `US West`. This will slow down the performance of CF. Is it possible to give priority to connect to components in same region?
* Can load balancer be across region? The router VMs in different regions need to be in the backend of a same LB.

**Comment by dpb587-pivotal** [comment]
Re: prioritization - this is primarily a concern which should be handled outside of BOSH director. That is, individual releases may have different strategies and needs regarding how they handle WAN links, and that's something BOSH probably can't have enough insight into. However, BOSH should be able to provide tools which may help, such releases preferring their own AZ when constructing [links](http://bosh.io/docs/dns/#consuming-dns-job-templates).

Re: load balancer - depending on the IaaS and load balancers configuration, they may only support local instances. For IaaSes supporting references by name, if you have the same-named load balancer in each region, they would be attached to their local region's load balancer. For more complicated setups, this may require separate instance groups with unique vm types/extensions or, in a possible future, [VM type variations](https://github.com/cloudfoundry/bosh-notes/blob/8d376b4a71a0170f6ccbd4e2d81c85f6bde1b9e6/proposals/multi-cpi-v2.md#L25)

In general, I do not think there has been much testing of cf-deployment in a traditional configuration in a cross-region setup. There are several different types of topologies which could theoretically work, but they're not all as practical and efficient. I'm sure the cf-dev list would be curious if you do some research in this area.

Does that help clarify things a bit?

**Comment by bingosummer** [comment]
Thanks @dpb587-pivotal . I'm working on the doc of multi-cpi on azure. I use the multi-cpi feature to deploy a single cf-deployment across Azure and Azure China. `z1` is in Azure Cloud, and `z2` is in Azure China Cloud. The performance is slower than one deployment in a region, because the CF components in `z1` may connect to components in `z2`. That's why I asked the questions.
I agree with you that the setup would basically work, but no guarantee on the performance. Anyway, I will submit a PR once the guide-multi-cpi-azure.md is done.
