### ISSUE TITLE
Change all occurrences of `resource_pools` to `vm_types/vm_extensions`

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/docs-bosh#551]
`resource_pools` is legacy v1 manifest lingo that is difficult to translate into the v2 world, if you don't know the history. I propose to change all occurrences of `resource_pools` to `vm_types` – except in documents about v1 manifests.

I'm not sure, however, if it helps to always include `vm_extensions` as well – it doesn't really read well to always see `vm_types/vm_extensions`. Could we maybe just mention generically somewhere that `vm_extensions` can contain all `cloud_properties` that `vm_types` allow? 

wdyt?

**Comment by dpb587-pivotal** [comment]
I definitely agree with this. I've been changing them occasionally as I run into them, but feel free to work on them in bulk (aside from explicitly v1 manifests, as you mentioned).

In general, I don't think it makes sense to separate `vm_types` and `vm_extensions`. I'd like to see those properties referred to just as "VM cloud properties" or something. Then, in general, `vm_types` and `vm_extensions` should suggest they support VM cloud properties (as opposed to Network/Disk/~AZ).
