### ISSUE TITLE
document blobstore options

### ISSUE THREAD

**Issue by dpb587-pivotal** [cloudfoundry/docs-bosh#576]
Migrated from cloudfoundry/bosh-cli#90...

> We had to hunt down the the new blobstore configuration syntax. We found it in a [comment](https://github.com/cloudfoundry/bosh-cli/blob/master/releasedir/fs_config.go#L9-L22).
> 
> This should be documented somewhere since it is different from the old bosh-cli (Ruby).

**Comment by ssapra** [comment]
Does this page document the options? https://bosh.io/docs/release-blobstore/ 

If so, we can close this issue.

**Comment by dpb587-pivotal** [comment]
I think so; previously that page was showing the Ruby CLI config scheme.
