### ISSUE TITLE
Need to use bbr.yml in boshlite creation

### ISSUE THREAD

**Issue by arpitvipulsharma** [cloudfoundry/docs-bosh#621]
In boshlite setup, generally deployment runs inside of director.  I tried to update the director with create-env command(for bbr.yml) and deployment got affected, I was pretty sure about it. Its really painful. My suggestion is that somebody should update the documentation to include this bbr.yml file in bosh creation command as well. I remember, earlier this job was already included. Bosh backup should be part to bosh.io. 
Just a suggestion.

**Comment by jfmyers9** [comment]
Hi @arpitvipulsharma,

BOSH Lite is intended to be used as an ephemeral development workflow, and is not equipped to support production style workloads. For these reasons, we don't plan on adding the `bbr.yml` to the BOSH Lite documentation as in general users shouldn't be backing up and restoring their BOSH Lite environments. Sorry for the inconvenience. Let us know if you have any further questions.

Best,

@jfmyers9 && @belinda-liu, CF BOSH
