### ISSUE TITLE
"What is a Stemcell" Out of Date

### ISSUE THREAD

**Issue by dfreilich** [cloudfoundry/docs-bosh#642]
The [docs](http://bosh.cloudfoundry.org/docs/stemcell/) say: 
```
Cloud Foundry currently supports Ubuntu Trusty and CentOS 6.5 on vSphere, AWS, OpenStack, and vCloud infrastructures.
```
Currently, however, we also support (and encourage) Xenial, and have upgraded to CentOS 7, as well as a variety of Window infrastructures.

**Comment by belinda-liu** [comment]
Hey @dfreilich,

Thanks for pointing this out! I've updated the docs to point to the stemcells page instead, so hopefully it will be more resilient.
