### ISSUE TITLE
Wrong information on persistent disk

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry/docs-bosh#660]
We just found out the statement "If you attach a persistent disk to a virtual machine and then stop, terminate, or delete the VM, your persistent disk data remains intact" is inaccurate.

In vSphere at least, if you delete the BOSH Director, the attached persistent will also be deleted. This is the most disastrous since you lose the whole control plane and very likely need to rebuild the whole foundation.

- In the case of BOSH Director, the VM can be shutdown, but NOT deleted, if you want to keep the persistent disk.

**Comment by beyhan** [comment]
Hi @ywei2017,

could you please provide the link to the documentation you are referencing.

**Comment by ywei2017** [comment]
Hi, @beyhan See the 2nd paragraph in [Persistent Disks](https://bosh.io/docs/persistent-disks/):

"If you attach a persistent disk to a virtual machine and then stop, terminate, or delete the VM, your persistent disk data remains intact. Attaching the persistent disk to another VM allows you to access your data."

I did more testing yesterday, and can confirm that "deleting the VM" will definitely wipe out the persistent disk -- for all VMS (not just the director).

Thanks
Yansheng

**Comment by beyhan** [comment]
Hi @ywei2017,

can you provide us with steps to reproduce the issue. Also the versions for director, CPI and stemcell you are using.

For all persistent disks created by the Director and attached to a VM, there is the concept of [orphaned disks](https://bosh.io/docs/persistent-disks/#orphaned-disks). When a VM is deleted by the Director, the persistent disk will stay as it is for the time configure in [max_orphaned_age_in_days](https://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh#p%3ddirector.disks.max_orphaned_age_in_days).

**Comment by ywei2017** [comment]
@beyhan It's true that persistent disks are orphaned, and kept when BOSH Director deletes a deployment. But the documentation uses the general phrase "delete a VM", which is generally understood as from the IaaS console.

We use vSphere. From the vSphere console, right click on a VM, and "Power Off Guest OS", then "Delete from Disk", which is the typical sequence of "delete a VM". When you do that, any persistent disk attached to the VM is gone.

To address the confusion, there needs to be a **WARNING**, like what I put in my original post. This is particularly important concerning the Director itself, and it happened to us last week.

Thanks
Yansheng

**Comment by beyhan** [comment]
@ywei2017 I see. Is this the default behaviour on vSphere? What happens if you execute `bosh delete-vm`? Is the persistent disk deleted? 

E.g. the default behaviour on AWS is to [keep the attached disk](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html#preserving-volumes-on-termination). On OpenStack is the same.

**Comment by ywei2017** [comment]
@beyhan Yes, this is the default behavior for vSphere.

However, running `bosh delete-vm` does NOT delete the disk. In our case, the bosh resurrector kicks in, re-creates the VM and reattach the disk.

Thanks
Yansheng

**Comment by beyhan** [comment]
@ywei2017 Would you mind to open a PR, with your suggestions to improve the persistent disk documentation?

**Comment by ywei2017** [comment]
@beyhan . Np, see [PR 670](https://github.com/cloudfoundry/docs-bosh/pull/670)

**Comment by h4xnoodle** [comment]
Closing as we've addressed the problem and the docs PR is submitted & being reviewed.
