### ISSUE TITLE
Director HTTP API - Tasks section does not include `limit` or `verbose`

### ISSUE THREAD

**Issue by a2geek** [cloudfoundry/docs-bosh#717]
The Task API supports a `limit` and a `verbose` flag in the queries but they are not documented. They do happen to be in a sample but there is no mention of them otherwise.

Specifically, I was reviewing this section: https://bosh.io/docs/director-api-v1/#tasks

I found the options trying to figure out if there is a "size" parameter (there is not, but _limit_ is what I needed). 

I have no idea what the `verbose` numbers mean without digging deeper into the CLI source.

Please update the documentation so others don't have to dig like I did.  Thanks!

**Comment by ssapra** [comment]
Fixed in https://github.com/cloudfoundry/docs-bosh/commit/89242da76509416608d342a5be33ebd93b7ac932
