### ISSUE TITLE
Dead link in azure-init

### ISSUE THREAD

**Issue by schmidtsv** [cloudfoundry/docs-bosh#771]
https://github.com/cloudfoundry/docs-bosh/blob/master/content/init-azure.md?plain=1#L9 link seems to be dead an leaves to a 404 page

**Comment by beyhan** [comment]
@schmidtsv do you want to provide a pr for this? It looks like the place of the templates changed to https://github.com/Azure/azure-quickstart-templates/tree/master/application-workloads/bosh/bosh-setup.

**Comment by mvach** [comment]
Hi I created a fix for this issue: https://github.com/cloudfoundry/docs-bosh/pull/772
