### ISSUE TITLE
Switching from local to s3 release blobstore

### ISSUE THREAD

**Issue by dpb587-pivotal** [cloudfoundry/docs-bosh#94]
Had a question from a release developer—they followed the [create-release](http://bosh.io/docs/create-release.html) doc which suggests they use a local blobstore, but then were getting ready to share their release outside their workstation. Suggested S3 and following [s3-create-release](http://bosh.io/docs/s3-release-blobstore.html), but there's no docs guiding how to switch blobstore. I think it's not just `bosh upload blobs` since `blobs/*` is full of symlinks already.

**Comment by voelzmo** [comment]
We use something like https://gist.github.com/voelzmo/afc3baba20685992e88a784b02223de0 to move blobs from one blobstore to another. Would be great to have that in BOSH as built-in functionality, though :)

Probably just too lazy to submit a PR yet. What do you think, @cppforlife, should we have something like `bosh migrate blobstore`?
